### ISSUE TITLE
opening browser external to rPi

### ISSUE THREAD

**Issue by dlarue** [benb116/Etch#2]
Looks like a fun project and love the effort to make it looks like a BIG ETCH-a-Sketch.

I was playing with the code a bit and trying to figure out installation and how it works when I noticed I could not connect to the server on the rPi from my desktop. Learned a bit about Flask....

I did get the client to run from my desktop with this in server.py:
        #socketio.run(app)
        socketio.run(app, host='0.0.0.0', port=5000, debug=True)

I also changed the two references to "localhost" in public/art/index.html to the hostname of my rPi.

Now if I can only solve the  socketio version error the server spits out:
The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)

**Comment by benb116** [comment]
Hi Doug, not sure what might be causing that error. For reference, I am using python 3.8 and flask-socketio version 4.3.1. The frontend is pulling the v2 socket-io library. Which versions of these various libraries are you using? See [Here](https://github.com/miguelgrinberg/Flask-SocketIO/issues/1426) for a possible solution. Also please see [This](https://flask-socketio.readthedocs.io/en/latest/#version-compatibility) to make sure your SocketIO library is compatible with the flask-socketIO library.

**Comment by dlarue** [comment]
I downgraded the flask-socketio lib to 3.0.0 and the error disappeared. I was then getting origin errors so I added this to accept all origins and that error went away. BTW, I'm using Chrome for the client:
#DJL socketio = SocketIO(app)
socketio = SocketIO(app,cors_allowed_origins="*")

I just can't get it to render anything. My web page is all gray but for a little text box in the upper left side and a Fast check box.
I type Homer into the box and hit enter and nothing happens and the server spits out the following with no change on the client:
(env) pi@dougs-audiobot:~/Etch/rPi $ python server.py 
begin
begin
(1110) wsgi starting up on http://0.0.0.0:5000
(1110) accepted ('192.168.68.116', 59212)
192.168.68.116 - - [18/Jan/2021 14:09:52] "GET /socket.io/?EIO=3&transport=polling&t=NSNZ1HD HTTP/1.1" 200 429 0.004047
(1110) accepted ('192.168.68.116', 59214)
192.168.68.116 - - [18/Jan/2021 14:09:52] "GET /socket.io/?EIO=3&transport=polling&t=NSNZ1Iy&sid=9a9841431bd74feab0e9f511e3f96cd1 HTTP/1.1" 200 246 0.001782
192.168.68.116 - - [18/Jan/2021 14:09:52] "GET /socket.io/?EIO=3&transport=polling&t=NSNZ1JI&sid=9a9841431bd74feab0e9f511e3f96cd1 HTTP/1.1" 200 246 0.001304
(1110) accepted ('192.168.68.116', 59220)
art/Homer.json
192.168.68.116 - - [18/Jan/2021 14:10:00] "GET /art/Homer.json HTTP/1.1" 200 9140 0.005085

pip list on the rpi:
(env) pi@dougs-audiobot:~/Etch/rPi $ pip list
Package         Version
--------------- ---------
bidict          0.21.2
certifi         2018.8.24
chardet         3.0.4
click           7.1.2
dnspython       1.16.0
eventlet        0.30.0
Flask           1.1.2
Flask-Ext       0.1
Flask-SocketIO  3.0.0
gpio            0.3.0
greenlet        1.0.0
idna            2.6
itsdangerous    1.1.0
Jinja2          2.11.2
MarkupSafe      1.1.1
netifaces       0.10.6
pi-utils        0.0.1
pip             20.3.3
pkg-resources   0.0.0
python-apt      1.8.4.3
python-engineio 3.14.2
python-socketio 5.0.0
requests        2.21.0
setuptools      3.3
six             1.12.0
socketio        0.2.1
ssh-import-id   5.7
urllib3         1.24.1
virtualenv      15.1.0
Werkzeug        1.0.1
wheel           0.36.2

**Comment by benb116** [comment]
That seems correct for the server side of things. Could you attempt to run this again with the DevTools console open on the frontend browser? The output should look like this:

<img width="629" alt="Screen Shot 2021-01-18 at 5 16 19 PM" src="https://user-images.githubusercontent.com/2565688/104967261-eec5f900-59b0-11eb-9aac-afa762a8ab66.png">

If your console looks the same, I would add some print statements to [this](https://github.com/benb116/Etch/blob/212a8fec2dea0faf8f2097965b56690204802905/rPi/server.py#L89) function. This should be called once the frontend is finished its setup. See if those print statements are triggered. I wonder if there is still some websockets issues between client and server.

**Comment by benb116** [comment]
Actually, I just realized that the server is not printing "connected" in your log. Creating a connection over websockets is likely the gating issue. I'm not sure what could cause that though.

**Comment by dlarue** [comment]
Using that developer tools window, I saw some errors listed and it looks like it is still still an orgin issue:

﻿
2
(index):1 Access to fetch at 'http://192.168.68.122:5000/art/Homer.json' from origin 'http://dougs-audiobot.local:5000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by dlarue** [comment]
as mentioned by the error message I added mode: 'no-cors' to the public/index.html file and no more errors shown from developemnt tools screen. But still no rendering when I enter Homer.

        fetch('http://dougs-audiobot.local:5000'+url, {cache: 'reload'},{ mode: 'no-cors'})

Should I be seeing just a gray screen with that one test input box and check box? I really don't know what this is supposed to look like and was quite surprised the server.py code wasn't erroring out without a GPIO package, etc. I've connected no motor or encoder hardware yet. Just trying to get the screen to render the default designs.

The dev tool console looks like you posted but no drawing:

DevTools failed to load SourceMap: Could not load content for http://dougs-audiobot.local:5000/socket.io.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
(index):93 new link /art/Homer.json
(index):100 {name: "Homer", pxSpeed: 40, pxPerRev: 40, points: Array(884)}
(index):120 Time (min): 3.3012109375

**Comment by benb116** [comment]
At first the gray screen (and the input box and check box) should be all that is visible. Once you type in "Homer" and press enter, then the animation should start after about a second. There is code in the server file that only imports the GPIO package if the code is running on an rPi; if it isn't, then motor and sensor integration are not loaded.

It looks like the frontend is correctly getting the data from the backend. At this point, I'd guess the issue lies in the "on_clientArtReady" function running in the server. When the frontend has set everything up (which it has in your case), it sends a message over the socket to the server with the "clientArtReady" tag. 

Could you try adding some print statements to that function and see how far the server makes it through? When the server is finished, it should emit a "startTime" event to the client.

**Comment by dlarue** [comment]
I have been chasing down the "on_connect" method and how it's not getting called and printing. Went into public/index.html where it creates the socket and that is where the problem seems to be. No socket is getting connected. I added a log of the socket and looked in dev tools to expand the object and see "connected: false" so it's not creating the socket it would seem.
It looks to be creating the data just can't send it to the client for rendering...

print/debug added to public/index.html

   console.log('Pre-Connect');
    var socket = io.connect('http://localhost:5000');
    console.log(socket);
    socket.on('connect', function() {
        console.log('Connected');
    });

**Comment by benb116** [comment]
That's certainly odd. I'm afraid I'm at a loss for how to resolve the socket issue.

However, there is a workaround if you'd just like to play around with the display (i.e. without any motor/sensor integration): Immediately after [this line](https://github.com/benb116/Etch/blob/212a8fec2dea0faf8f2097965b56690204802905/rPi/public/index.html#L120) in the frontend code, add `Begin();` this will short-circuit the socket messages being sent and simply start drawing immediately.

Sorry I can't be of more help with regard to the socket error; I'll keep playing around with it.

**Comment by dlarue** [comment]
Thanks, the addition of Begin() does start the client rendering.  I will try booting a Ubuntu 20.04 image and see if it works there with later python versions even though I'm running python 3.9. I suspect it's socketio version problems.

**Comment by dlarue** [comment]
On Lubuntu 20.04 all it took was this:
sudo apt install git python3-pip python3-socketio python3-flask-socketio python3-eventlet

I tried setting up using pip3 but I got client socket version issues again. Going all native worked and here is what the package versions played out to be using the native install listed above:

ubuntu@ubuntu:~/Etch/rPi$ pip3 list
Package                 Version      
----------------------- -------------
apt-xapian-index        0.49        
blinker                 1.4          
certifi                 2019.11.28  
chardet                 3.0.4        
Click                   7.0          
colorama                0.4.3        
command-not-found       0.3          
cryptography            2.8          
cupshelpers             1.0          
dbus-python             1.2.16      
defer                   1.0.6        
distro                  1.4.0        
distro-info             0.23ubuntu1  
dnspython               1.16.0      
entrypoints             0.3          
eventlet                0.25.1      
Flask                   1.1.1        
Flask-SocketIO          4.2.1        
galternatives           1.0.6        
greenlet                0.4.15      
httplib2                0.14.0      
idna                    2.8          
itsdangerous            1.1.0        
Jinja2                  2.10.1      
keyring                 18.0.1      
language-selector       0.1          
launchpadlib            1.10.13      
lazr.restfulclient      0.14.2      
lazr.uri                1.0.3        
lubuntu-update-notifier 0.1          
MarkupSafe              1.1.0        
monotonic               1.5          
netifaces               0.10.4      
oauthlib                3.1.0        
olefile                 0.46        
pexpect                 4.6.0        
Pillow                  7.0.0        
pip                     20.0.2      
pycairo                 1.16.2      
pycups                  1.9.73      
PyGObject               3.36.0      
pyinotify               0.9.6        
PyJWT                   1.7.1        
pymacaroons             0.13.0      
PyNaCl                  1.3.0        
pyOpenSSL               19.0.0      
PyQt5                   5.14.1      
python-apt              2.0.0        
python-debian           0.1.36ubuntu1
python-engineio         3.11.1      
python-socketio         4.4.0        
pyxdg                   0.26        
PyYAML                  5.3.1        
reportlab               3.5.34      
requests                2.22.0      
requests-unixsocket     0.2.0        
SecretStorage           2.3.1        
setuptools              45.2.0      
simplejson              3.16.0      
sip                     4.19.21      
six                     1.14.0      
systemd-python          234          
ubuntu-advantage-tools  20.3        
ubuntu-drivers-common   0.0.0        
ufw                     0.36        
unattended-upgrades     0.1          
urllib3                 1.25.8      
usb-creator             0.3.7        
wadllib                 1.3.3        
Werkzeug                0.16.1      
wheel                   0.34.2      
xkit                    0.0.0        
ubuntu@ubuntu:~/Etch/rPi$
